version: "3.8"
services: 
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: gdsc
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql

  adminer:
      container_name: adminer
      image: adminer
      ports:
        - "8081:8080"
