version: '3.8'

services:
  app:
    build:
      context: .
      target: production-stage
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:ro
