version: "3.8"
services:
  app:
    build: .
    container_name: edupass-be
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: edupass
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
