version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=mysql
      - DB_PORT=3306
      - MAIL_USER=${MAIL_USER}
      - MAIL_CLIENT_ID=${MAIL_CLIENT_ID}
      - MAIL_CLIENT_SECRET=${MAIL_CLIENT_SECRET}
      - MAIL_REDIRECT_URL=${MAIL_REDIRECT_URL}
      - MAIL_REFRESH_TOKEN=${MAIL_REFRESH_TOKEN}
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - mysql
    command: npm run dev

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  mysql-data:
