version: '3.8'

services:
  app:
    build:
      context: .
      target: development-stage
      args:
        NODE_ENV: development
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
